import { Lightbulb } from 'lucide-react';
import { motion } from 'framer-motion';

export default function ExplanationPanel({ title, content }) {
  return (
    <motion.div 
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="bg-surface/50 border border-gray-800 rounded-2xl p-6"
    >
      <div className="flex items-center gap-3 mb-4 text-yellow-500">
        <Lightbulb className="w-6 h-6" />
        <h3 className="font-semibold text-lg">Deep Dive</h3>
      </div>
      <h4 className="text-white font-medium mb-2">{title}</h4>
      <p className="text-gray-400 leading-relaxed text-sm">
        {content || "This panel will provide extra context generated by the AI based on the current scene. If you pause, we can break down the exact physics equations happening on screen."}
      </p>
    </motion.div>
  );
}
