import { Play, Pause, Maximize, Volume2 } from 'lucide-react';

export default function LessonPlayer({ title, placeholderType = 'video' }) {
  return (
    <div className="w-full max-w-4xl mx-auto rounded-2xl overflow-hidden bg-surface shadow-2xl border border-gray-800">
      <div className="relative aspect-video bg-black flex flex-col items-center justify-center">
        {/* Placeholder Content */}
        <div className="absolute inset-0 flex flex-col items-center justify-center bg-gradient-to-br from-gray-900 to-gray-800 text-gray-400">
          <Play className="w-20 h-20 mb-4 opacity-50" />
          <p className="text-xl font-medium">Animation Service Placeholder</p>
          <p className="text-sm mt-2">({placeholderType} format will load here)</p>
        </div>

        {/* Controls Overlay */}
        <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/80 to-transparent p-4 flex items-center justify-between opacity-0 hover:opacity-100 transition-opacity">
          <div className="flex items-center gap-4 text-white">
            <button className="hover:text-primary transition-colors"><Play className="w-6 h-6" /></button>
            <button className="hover:text-primary transition-colors"><Volume2 className="w-5 h-5" /></button>
            <div className="text-sm font-medium">0:00 / 5:30</div>
          </div>
          <div className="flex items-center text-white">
            <button className="hover:text-primary transition-colors"><Maximize className="w-5 h-5" /></button>
          </div>
        </div>
      </div>
      <div className="p-6">
        <h2 className="text-2xl font-semibold mb-2">{title || 'Introduction to the Topic'}</h2>
        <p className="text-gray-400 text-sm">Interactive animation generated by Animax AI</p>
      </div>
    </div>
  );
}
